apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql # RC的名称，全局唯一
spec:
  replicas: 1 # Pod副本期待数量
  selector:
    app: mysql # 符合目标的pod拥有此标签
  template:
    metadata:
      labels:
        app: mysql # Pod副本拥有的标签，对于RC的selector
    spec:
      containers:
        - name: mysql # docker container name
          image: mysql # docker image name
          ports:
            - containerPort: 3306 # 端口号
          env:
            - name: MYSQL_ROOT_PASSWORD # 注入环境变量
              value: "123456"
