apiVersion: v1
kind: Pod
metadata:
  name: name
  namespace: ns
  labels:
    app: name
  annotations:
    - name: name12
    - age: 12
spec:
  containers:
    - name: name
      image: image
      imagePullPolicy: IfNotPresent
      command:
        - cmd
      args:
        - args
      workingDir: dir
      volumeMounts:
        - mountPath: path
          name: volume1
          readOnly: true
      ports:
        - containerPort: 11111
          hostIP: 111.111.1.11
          hostPort: 1111
      env:
        - name: env
          value: value1
      resources:
        requests:
          cpu: 100m
          memory: 1024
        limits:
          cpu: 100m
          memory: 1024
      livenessProbe:
        exec:
          command:
            - cmd
        httpGet:
          port: 11111
          path: 11
          host: 1
          scheme: 1
          httpHeaders:
            - name: 1
              value: 1
        tcpSocket:
          port: 11
        initialDelaySeconds: 0
        timeoutSeconds: 0
        periodSeconds: 0
        successThreshold: 0
        failureThreshold: 0
      securityContext:
        privileged: false
  restartPolicy: Always
  nodeSelector:
    name: a
  imagePullSecrets:
    - name: 1
  hostNetwork: false
  volumes:
    - name: volume1
      emptyDir:
        {}
      hostPath:
        path: 1
      secret:
        secretName: 1
        items:
          - key: 1
            path: 1
      configMap:
        name: 1
        items:
          - key: 1
            path: 1