name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install --file ./java-tools/pom.xml
    - name: Deploy with Maven
      run: mvn deploy --file ./java-tools/pom.xml
    - name: Build docker Image
      run: docker build /home/runner/.m2/repository/com/github/freshchen/java-tools/0.0.1/ --file ./java-tools/src/main/resources/Dockerfile --tag freshchen/java-tools:latest
    - name: docker login
      run: docker login -u freshchen -p ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: docker push
      run: docker push freshchen/java-tools:latest
    - name: Restart Service
      run: sshpass -p ${{ secrets.PWD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} ${{ secrets.DOCKER_COMPOSE_CMD }}
