name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install --file ./java-tools/pom.xml
    - name: Build docker Image
      run: docker build . --file ./java-tools/src/main/resources/Dockerfile --tag freshchen/java-tools:latest
    - name: docker login
      run: docker login -u freshchen -p d7359c55-2435-424d-8b1d-4918fc42f504
    - name: docker push
      run: docker push freshchen/java-tools:latest
